name: Build, Test, and Release

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'   # adjust as needed

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    #- name: Test
     # run: dotnet test --configuration Release --no-build --verbosity normal

    #- name: Build Installer1
    #  run: devenv.exe "BehringerMonitor.sln" /build "Release" /project "BehringerMonitor.Installer\BehringerMonitor.Installer.vdproj"

    - name: Locate devenv
      run: |
          $devenv = & vswhere.exe '-property' productPath
          Write-Output "$devenv"
          Split-Path -Path $devenv -Parent | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Print path
      run: echo $env:GITHUB_PATH

    - name: Build Installer
      run: devenv.com "BehringerMonitor.sln" /build "Release" /project "BehringerMonitor.Installer\BehringerMonitor.Installer.vdproj"

    - name: Publish WPF app
      run: dotnet publish BehringerMonitor\BehringerMonitor.csproj -c Release -o publish

    - name: Publish WPF app (self-contained)
      run: dotnet publish BehringerMonitor\BehringerMonitor.csproj -c Release -o publish-self-contained -r win-x64 --self-contained true

    - name: Generate release tag
      id: tag
      shell: pwsh
      run: |
        $tag = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd-HH-mm-ss")
        echo "tag=$tag" >> $env:GITHUB_OUTPUT

    - name: Zip published output
      shell: pwsh
      run: |
        Compress-Archive -Path publish\* -DestinationPath BehringerMonitor-${{ steps.tag.outputs.tag }}.zip
        Compress-Archive -Path publish-self-contained\* -DestinationPath BehringerMonitor-${{ steps.tag.outputs.tag }}-self-contained.zip
        Compress-Archive -Path BehringerMonitor.Installer\Release\* -DestinationPath BehringerMonitor-${{ steps.tag.outputs.tag }}-installer.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        name: "Release ${{ steps.tag.outputs.tag }}"
        files: |
         BehringerMonitor-${{ steps.tag.outputs.tag }}.zip
         BehringerMonitor-${{ steps.tag.outputs.tag }}-self-contained.zip
         BehringerMonitor-${{ steps.tag.outputs.tag }}-installer.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
